const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const SKEY='bdeTestLabState.v2',QKEY='bdeTestLabCustomQuestions.v2';
const blank={attempts:[],mistakes:{},mastered:{},notes:{},daily:{},recentQuestions:[],settings:{dailyGoal:40}};
let state=loadState(),questions=[],test=null,installPrompt=null;
function clone(x){return JSON.parse(JSON.stringify(x))}
function loadState(){try{return {...clone(blank),...(JSON.parse(localStorage.getItem(SKEY))||{})}}catch{return clone(blank)}}
function loadCustom(){try{return JSON.parse(localStorage.getItem(QKEY))||[]}catch{return[]}}
function save(){localStorage.setItem(SKEY,JSON.stringify(state));renderAll()}
function saveCustom(qs){localStorage.setItem(QKEY,JSON.stringify(qs));questions=[...(window.BDE_QUESTIONS||[]),...qs];renderAll()}
function today(){return new Date().toISOString().slice(0,10)}
function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function pct(a,b){return b?Math.round(a/b*100):0}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function qById(id){return questions.find(q=>q.id===id)}
function activeMistakes(){return Object.values(state.mistakes).filter(m=>!state.mastered[m.questionId]).map(m=>qById(m.questionId)).filter(Boolean)}
function download(name,text,type='application/json'){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function go(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('#title').textContent={panel:'Panel',test:'Hacer test',fallos:'Registro de fallos',banco:'Banco de preguntas',ajustes:'Ajustes'}[v]||'Panel';$('#sidebar').classList.remove('open');renderAll()}
function getPool(tipo,bloque){let p=tipo==='fallos'?activeMistakes():questions.filter(q=>q.type===tipo);return bloque&&bloque!=='Todos los bloques'?p.filter(q=>q.section===bloque):p}
function fillBloques(){let tipo=$('#tipo').value,prev=$('#bloque')?.value,p=getPool(tipo);let secs=['Todos los bloques',...[...new Set(p.map(q=>q.section))].sort()];$('#bloque').innerHTML=secs.map(s=>`<option ${s===prev?'selected':''}>${s}</option>`).join('');$('#penaliza').checked=tipo!=='capacidades';updatePoolInfo()}
function updatePoolInfo(){let tipo=$('#tipo').value,bloque=$('#bloque').value,num=+$('#num').value||20,p=getPool(tipo,bloque),r=new Set(state.recentQuestions||[]),fresh=p.filter(q=>!r.has(q.id)).length;let msg=`Banco disponible: ${p.length} preguntas`;if(tipo!=='fallos')msg+=` · no vistas recientemente: ${fresh}`;if(num>p.length)msg+=` · has pedido ${num}, se usarán ${p.length}`;if(p.length<15&&tipo!=='fallos')msg+=' · este bloque es pequeño';$('#poolInfo').textContent=msg}
function startFromForm(){startTest({tipo:$('#tipo').value,bloque:$('#bloque').value,modo:$('#modo').value,num:+$('#num').value||20,secs:+$('#secs').value||75,penaliza:$('#penaliza').checked,noRepeat:$('#noRepeat').checked})}
function selectPool(pool,cfg){let target=Math.min(cfg.num,pool.length);if(!cfg.noRepeat||cfg.tipo==='fallos')return shuffle(pool).slice(0,target);let r=new Set(state.recentQuestions||[]);return [...shuffle(pool.filter(q=>!r.has(q.id))),...shuffle(pool.filter(q=>r.has(q.id)))].slice(0,target)}
function startTest(cfg){let p=getPool(cfg.tipo,cfg.bloque);if(!p.length){alert('No hay preguntas para esa selección.');return}let original=p.length;p=selectPool(p,cfg);if(cfg.num>original)alert(`Solo hay ${original} preguntas para esa selección. Harás ${p.length}.`);test={cfg,qs:p.map(q=>({...q,options:shuffle(q.options)})),i:0,ans:{},notes:{},end:Date.now()+p.length*cfg.secs*1000,timer:null};$('#setup').classList.add('hidden');$('#resultado').classList.add('hidden');$('#runner').classList.remove('hidden');tick();test.timer=setInterval(tick,500);renderQ()}
function tick(){if(!test)return;let r=Math.max(0,test.end-Date.now());$('#timer').textContent=String(Math.floor(r/60000)).padStart(2,'0')+':'+String(Math.floor((r%60000)/1000)).padStart(2,'0');if(r<=0)finish()}
function renderQ(){let q=test.qs[test.i],a=test.ans[q.id];$('#meta').textContent=`${test.i+1}/${test.qs.length} · ${test.cfg.tipo}`;$('#rTitulo').textContent=q.section;$('#prog').style.width=(test.i+1)/test.qs.length*100+'%';$('#fuente').textContent=q.source+(q.official?' · oficial':'');$('#tema').textContent=q.topic;$('#enunciado').textContent=q.question;$('#nota').value=test.notes[q.id]||state.notes[q.id]||'';$('#opciones').innerHTML=q.options.map(o=>`<button class="option ${a===o.key?'selected':''}" data-k="${o.key}"><span class="letter">${o.key}</span><span>${o.text}</span></button>`).join('')+'<div id="fb"></div>';$$('.option').forEach(b=>b.onclick=()=>{test.ans[q.id]=b.dataset.k;renderQ()});$('#prev').disabled=test.i===0;$('#next').textContent=test.i===test.qs.length-1?'Ver resultado':'Siguiente';feedback()}
function feedback(){let q=test.qs[test.i],a=test.ans[q.id],fb=$('#fb');if(test.cfg.modo!=='practica'||!a){fb.innerHTML='';return}$$('.option').forEach(b=>{if(b.dataset.k===q.answer)b.classList.add('correct');if(b.dataset.k===a&&a!==q.answer)b.classList.add('wrong')});let ok=a===q.answer;fb.className='feedback '+(ok?'ok':'bad');fb.innerHTML=ok?`Correcta. ${q.explanation||''}`:`Fallada. Correcta: <strong>${q.answer}</strong>. ${q.explanation||'Añade una nota y repásala.'}`}
function move(d){let q=test.qs[test.i];test.notes[q.id]=$('#nota').value.trim();if(d>0&&test.i===test.qs.length-1)return finish();test.i=Math.max(0,Math.min(test.qs.length-1,test.i+d));renderQ()}
function finish(){if(!test)return;clearInterval(test.timer);let qcur=test.qs[test.i];if(qcur)test.notes[qcur.id]=$('#nota').value.trim();let correct=0,wrong=0,blank=0,score=0,topics={};for(let q of test.qs){let a=test.ans[q.id]||null,ok=a===q.answer;if(!a)blank++;else if(ok)correct++;else wrong++;score+=ok?1:(!a?0:(test.cfg.penaliza?-0.33:0));let k=q.section+' · '+q.topic;topics[k]??={seen:0,ok:0,wrong:0};topics[k].seen++;if(ok)topics[k].ok++;else if(a)topics[k].wrong++;if(test.notes[q.id])state.notes[q.id]=test.notes[q.id];if(a&&!ok){let m=state.mistakes[q.id]||{questionId:q.id,timesWrong:0,timesSeen:0,selected:[],firstWrongAt:new Date().toISOString()};m.timesWrong++;m.timesSeen++;m.lastWrongAt=new Date().toISOString();m.selected.push({answer:a,at:new Date().toISOString()});state.mistakes[q.id]=m;delete state.mastered[q.id]}else if(state.mistakes[q.id])state.mistakes[q.id].timesSeen=(state.mistakes[q.id].timesSeen||0)+1}let total=test.qs.length,grade=Math.max(0,score/total*10),ids=test.qs.map(q=>q.id),att={at:new Date().toISOString(),type:test.cfg.tipo,section:test.cfg.bloque,total,correct,wrong,blank,score,grade,penalty:test.cfg.penaliza,questionIds:ids};state.attempts.push(att);state.recentQuestions=[...ids,...(state.recentQuestions||[]).filter(id=>!ids.includes(id))].slice(0,250);state.daily[today()]=(state.daily[today()]||0)+total;test=null;save();$('#runner').classList.add('hidden');$('#setup').classList.remove('hidden');showResult(att,topics)}
function showResult(a,topics){let rows=Object.entries(topics).sort((x,y)=>x[1].ok/x[1].seen-y[1].ok/y[1].seen).map(([k,v])=>`<tr><td>${k}</td><td>${v.ok}/${v.seen}</td><td>${pct(v.ok,v.seen)}%</td></tr>`).join('');$('#resultado').classList.remove('hidden');$('#resultado').innerHTML=`<h3>Resultado</h3><div class="resultgrid"><div><span>Nota</span><strong>${a.grade.toFixed(2)}</strong></div><div><span>Aciertos</span><strong>${a.correct}/${a.total}</strong></div><div><span>Fallos</span><strong>${a.wrong}</strong></div></div><p>${a.penalty?'Con penalización -0,33.':'Sin penalización.'}</p><table><thead><tr><th>Tema</th><th>Aciertos</th><th>%</th></tr></thead><tbody>${rows}</tbody></table><div class="actions"><button class="primary" onclick="go('fallos')">Ver fallos</button><button class="secondary" onclick="go('test')">Otro test</button></div>`}
function streak(){let d=new Date(),s=0;while((state.daily[d.toISOString().slice(0,10)]||0)>0){s++;d.setDate(d.getDate()-1)}return s}
function renderPanel(){let done=state.attempts.reduce((s,a)=>s+a.total,0),ok=state.attempts.reduce((s,a)=>s+a.correct,0),vivos=activeMistakes().length,acc=pct(ok,done);$('#sPreg').textContent=done;$('#sAcc').textContent=acc+'%';$('#sFallos').textContent=vivos;$('#sRacha').textContent=streak();$('#dominio').textContent=(done?Math.max(0,Math.min(100,Math.round(acc-vivos*.5))):0)+'%';$('#dominioSub').textContent=vivos?`${vivos} fallos por repasar.`:(done?'Sin fallos vivos. Haz simulacro.':'Empieza un test.');let td=state.daily[today()]||0;$('#goalText').textContent=`${td} / ${state.settings.dailyGoal}`;$('#goalBar').style.width=Math.min(100,pct(td,state.settings.dailyGoal))+'%';renderHeat();renderReco()}
function renderHeat(){let map={};Object.values(state.mistakes).forEach(m=>{let q=qById(m.questionId);if(!q||state.mastered[q.id])return;let k=q.section+' · '+q.topic;map[k]=(map[k]||0)+(m.timesWrong||0)});let arr=Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,8);$('#heat').classList.toggle('empty',!arr.length);$('#heat').innerHTML=arr.length?arr.map(([k,v])=>`<div class="weak"><strong>${k}</strong><span>${v} fallos</span><div class="bar"><i style="width:${Math.min(100,v*18)}%"></i></div></div>`).join(''):'Sin datos todavía.'}
function renderReco(){let vivos=activeMistakes();if(vivos.length){let q=vivos[0];$('#reco').innerHTML=`<div class="rec"><strong>Ahora toca repasar fallos</strong><p>Tienes ${vivos.length} fallos vivos. Empieza por ${q.section} · ${q.topic}.</p><button class="primary" onclick="go('test');startTest({tipo:'fallos',bloque:'Todos los bloques',modo:'practica',num:10,secs:90,penaliza:true})">Repasar 10</button></div>`}else{$('#reco').innerHTML=`<div class="rec"><strong>Primer entrenamiento</strong><p>Haz 20 preguntas de conocimientos con feedback. Luego el sistema montará tu lista de fallos.</p><button class="primary" onclick="go('test')">Empezar</button></div>`}}
function renderFallos(){let term=norm($('#buscarFallos').value),status=$('#estadoFallos').value;let arr=Object.values(state.mistakes).map(m=>({m,q:qById(m.questionId)})).filter(x=>x.q).filter(({q})=>status==='todos'||(status==='dominados'?state.mastered[q.id]:!state.mastered[q.id]));if(term)arr=arr.filter(({q})=>norm(q.question+' '+q.topic+' '+q.section+' '+q.source).includes(term));arr.sort((a,b)=>new Date(b.m.lastWrongAt)-new Date(a.m.lastWrongAt));$('#listaFallos').classList.toggle('empty',!arr.length);$('#listaFallos').innerHTML=arr.length?arr.map(({m,q})=>`<article class="item"><header><div><h4>${q.section} · ${q.topic}</h4><span class="tag">${q.source}</span><span class="tag">${m.timesWrong} fallos</span>${state.mastered[q.id]?'<span class="tag">Dominada</span>':''}</div><button class="secondary" data-one="${q.id}">Repasar</button></header><p>${q.question}</p><p><strong>Correcta:</strong> ${q.answer}. <strong>Última tuya:</strong> ${m.selected?.at(-1)?.answer||'-'}</p><textarea rows="2" data-note="${q.id}" placeholder="Nota de memoria...">${state.notes[q.id]||''}</textarea><div class="actions"><button class="primary" data-save="${q.id}">Guardar nota</button><button class="secondary" data-master="${q.id}">${state.mastered[q.id]?'Reactivar':'Marcar dominada'}</button></div></article>`).join(''):'Aún no hay fallos registrados.';$$('[data-save]').forEach(b=>b.onclick=()=>{state.notes[b.dataset.save]=$(`[data-note="${b.dataset.save}"]`).value.trim();save()});$$('[data-master]').forEach(b=>b.onclick=()=>{state.mastered[b.dataset.master]?delete state.mastered[b.dataset.master]:state.mastered[b.dataset.master]=new Date().toISOString();save()});$$('[data-one]').forEach(b=>b.onclick=()=>{go('test');startSpecific(b.dataset.one)})}
function startSpecific(id){let q=qById(id);if(!q)return;test={cfg:{tipo:'fallos',modo:'practica',penaliza:true},qs:[{...q,options:shuffle(q.options)}],i:0,ans:{},notes:{},end:Date.now()+120000,timer:null};$('#setup').classList.add('hidden');$('#resultado').classList.add('hidden');$('#runner').classList.remove('hidden');tick();test.timer=setInterval(tick,500);renderQ()}
function renderBanco(){let total=questions.length,con=questions.filter(q=>q.type==='conocimientos').length,apo=questions.filter(q=>q.type==='apoyo').length,off=questions.filter(q=>q.official).length;$('#resumenBanco').innerHTML=`<article><span>Total</span><strong>${total}</strong></article><article><span>Conoc.</span><strong>${con}</strong></article><article><span>Apoyo</span><strong>${apo}</strong></article><article><span>Oficiales</span><strong>${off}</strong></article>`;let term=norm($('#buscarBanco').value),tipo=$('#tipoBanco').value;let arr=questions.filter(q=>tipo==='all'||q.type===tipo);if(term)arr=arr.filter(q=>norm(q.question+' '+q.topic+' '+q.section+' '+q.source).includes(term));$('#listaBanco').innerHTML=arr.slice(0,80).map(q=>`<article class="item"><header><div><h4>${q.section} · ${q.topic}</h4><span class="tag">${q.source}</span><span class="tag">${q.type}</span>${q.official?'<span class="tag">Oficial</span>':'<span class="tag">Simulacro</span>'}</div><strong>${q.answer||'?'}</strong></header><p>${q.question}</p></article>`).join('')+(arr.length>80?`<div class="empty">Mostrando 80 de ${arr.length}. Usa el buscador.</div>`:'')}
function renderAll(){renderPanel();renderFallos();renderBanco();fillBloques()}
function exportCsv(){let rows=[['bloque','tema','fuente','pregunta','correcta','veces_fallada','ultima_fecha','nota']];Object.values(state.mistakes).forEach(m=>{let q=qById(m.questionId);if(q)rows.push([q.section,q.topic,q.source,q.question,q.answer,m.timesWrong,m.lastWrongAt,state.notes[q.id]||''])});download('fallos-bde.csv',rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n'),'text/csv')}
function importProgress(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{state={...clone(blank),...JSON.parse(r.result)};save();alert('Progreso importado.')}catch{alert('JSON no válido')}};r.readAsText(f)}
function importQuestions(){try{let incoming=JSON.parse($('#importPregs').value);if(!Array.isArray(incoming))throw 0;saveCustom([...loadCustom(),...incoming]);$('#importPregs').value='';alert(`${incoming.length} preguntas importadas.`)}catch{alert('JSON no válido.')}}
function addManual(e){e.preventDefault();let q={id:'MAN_'+Date.now(),source:'Manual',number:0,type:'conocimientos',section:$('#mSec').value||'Manual',topic:$('#mTopic').value||'Sin tema',question:$('#mQ').value,options:['A','B','C','D'].map(k=>({key:k,text:$(`#m${k}`).value})),answer:$('#mAns').value,explanation:'',official:false};if(!q.question||q.options.some(o=>!o.text)){alert('Completa pregunta y opciones.');return}saveCustom([...loadCustom(),q]);$('#modal').close()}
function init(){$$('.nav').forEach(b=>b.onclick=()=>go(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#menu').onclick=()=>$('#sidebar').classList.toggle('open');$('#tipo').onchange=fillBloques;$('#bloque').onchange=updatePoolInfo;$('#num').oninput=updatePoolInfo;$('#noRepeat').onchange=updatePoolInfo;$('#start').onclick=startFromForm;$('#startFallos').onclick=()=>startTest({tipo:'fallos',bloque:'Todos los bloques',modo:'practica',num:10,secs:90,penaliza:true});$('#doFallos').onclick=()=>{go('test');startTest({tipo:'fallos',bloque:'Todos los bloques',modo:'practica',num:20,secs:90,penaliza:true})};$('#prev').onclick=()=>move(-1);$('#next').onclick=()=>move(1);$('#blank').onclick=()=>{let q=test.qs[test.i];delete test.ans[q.id];renderQ()};$('#finish').onclick=finish;$('#buscarFallos').oninput=renderFallos;$('#estadoFallos').onchange=renderFallos;$('#buscarBanco').oninput=renderBanco;$('#tipoBanco').onchange=renderBanco;$('#csv').onclick=exportCsv;$('#exportJson').onclick=()=>download('bde-test-lab-progreso.json',JSON.stringify(state,null,2));$('#importJson').onchange=importProgress;$('#reset').onclick=()=>{if(confirm('¿Seguro? Se borrará tu progreso.')){state=clone(blank);save()}};$('#importBtn').onclick=importQuestions;$('#manualBtn').onclick=()=>$('#modal').showModal();$('#mSave').onclick=addManual;if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#install').hidden=false});$('#install').onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#install').hidden=true}};renderAll()}
async function boot(){if(window.BDE_QUESTIONS_READY)await window.BDE_QUESTIONS_READY;questions=[...(window.BDE_QUESTIONS||[]),...loadCustom()];init()}
document.addEventListener('DOMContentLoaded',boot);
