const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const SKEY='bdeTestLabState.v2',QKEY='bdeTestLabCustomQuestions.v2';
const blank={attempts:[],mistakes:{},mastered:{},notes:{},daily:{},recentQuestions:[],settings:{dailyGoal:40}};
let state=loadState(),questions=[],test=null,installPrompt=null;
function clone(x){return JSON.parse(JSON.stringify(x))}
function loadState(){try{return {...clone(blank),...(JSON.parse(localStorage.getItem(SKEY))||{})}}catch{return clone(blank)}}
function loadCustom(){try{return JSON.parse(localStorage.getItem(QKEY))||[]}catch{return[]}}
function save(){localStorage.setItem(SKEY,JSON.stringify(state));renderAll()}
function saveCustom(qs){localStorage.setItem(QKEY,JSON.stringify(qs));questions=[...(window.BDE_QUESTIONS||[]),...qs];renderAll()}
function today(){return new Date().toISOString().slice(0,10)}
function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function pct(a,b){return b?Math.round(a/b*100):0}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function qById(id){return questions.find(q=>q.id===id)}
function activeMistakes(){return Object.values(state.mistakes).filter(m=>!state.mastered[m.questionId]).map(m=>qById(m.questionId)).filter(Boolean)}
function download(name,text,type='application/json'){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function escapeHtml(s){return String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function correctText(q){let o=(q.options||[]).find(x=>x.key===q.answer);return o?o.text:''}
function explanationFor(q){
  if(q.explanation&&String(q.explanation).trim())return q.explanation;
  const text=norm([q.section,q.topic,q.question,correctText(q)].join(' '));
  const rules=[
    [['inflacion','ipc','precios'],'la inflación se refiere a la variación general del nivel de precios. En macro, no basta con que suba un producto concreto: importa el comportamiento agregado y sostenido.'],
    [['pib','producto interior','valor anadido'],'el PIB mide producción final dentro de una economía durante un periodo. La clave es distinguir flujo de producción frente a riqueza acumulada o variables financieras.'],
    [['contabilidad nacional','ahorro','inversion'],'las identidades contables salen de igualar usos y recursos de la renta. En economía cerrada, sin sector público, el ahorro financia exactamente la inversión.'],
    [['is-lm','politica fiscal'],'en IS-LM, la política fiscal actúa primero sobre la demanda de bienes; por eso desplaza la IS. La política monetaria actúa primero sobre liquidez y tipos; por eso desplaza la LM.'],
    [['is-lm','politica monetaria'],'en IS-LM, aumentar liquidez desplaza LM a la derecha y presiona a la baja el tipo de interés. Una contracción monetaria hace lo contrario.'],
    [['demanda agregada','oferta agregada'],'el esquema DA-OA conecta producción, precios y shocks. La demanda agregada recoge gasto planeado; la oferta agregada depende de costes, capacidad productiva y expectativas.'],
    [['mercado laboral','desempleo','paro'],'las preguntas de mercado laboral suelen distinguir población activa, ocupados, desempleados e inactivos. La tasa de paro se calcula sobre la población activa.'],
    [['bce','banco central','tipos oficiales','politica monetaria'],'el banco central influye en la economía moviendo las condiciones financieras: tipos, crédito, expectativas y liquidez. La opción correcta suele respetar ese canal de transmisión.'],
    [['economia abierta','tipo de cambio','balanza de pagos','exportaciones','importaciones'],'en economía abierta hay que pensar en precios relativos internacionales. Una apreciación encarece exportaciones y abarata importaciones, mientras que la balanza de pagos registra relaciones con el exterior.'],
    [['multiplicador','propension marginal'],'el multiplicador depende de cuánto gasto adicional genera cada euro de renta. Si aumenta la propensión marginal a consumir, aumenta la cadena de gasto-renta.'],
    [['phillips','desempleo'],'la curva de Phillips relaciona inflación y desempleo en el corto plazo. A largo plazo, las expectativas y la tasa natural limitan ese trade-off.'],
    [['crecimiento','solow','productividad'],'el crecimiento sostenido de renta per cápita exige productividad o progreso tecnológico. Acumular capital por sí solo tiene rendimientos decrecientes.'],
    [['consumidor','restriccion presupuestaria','preferencias'],'en micro del consumidor hay que separar preferencias, restricción presupuestaria y elección óptima. La opción correcta normalmente identifica qué representa cada elemento.'],
    [['rms','relacion marginal de sustitucion','curva de indiferencia'],'la RMS es la pendiente de la curva de indiferencia: cuánto de un bien se sacrifica para obtener otro manteniendo la utilidad.'],
    [['elasticidad'],'la elasticidad mide sensibilidad porcentual. En demanda inelástica, la cantidad responde poco al precio y el ingreso total puede subir cuando sube el precio.'],
    [['competencia perfecta','precio aceptante','coste marginal'],'en competencia perfecta la empresa toma el precio como dado y produce donde precio e ingreso marginal igualan el coste marginal, si le compensa producir.'],
    [['coste marginal','costes'],'el coste marginal mide el coste de una unidad adicional. Es una idea clave para decisiones de producción y maximización de beneficios.'],
    [['monopolio'],'el monopolio enfrenta la demanda de mercado y sabe que para vender más debe bajar precio. Por eso su ingreso marginal queda por debajo del precio.'],
    [['oligopolio','cournot','bertrand'],'en oligopolio las decisiones estratégicas importan. Cournot suele modelar competencia en cantidades; Bertrand, competencia en precios.'],
    [['externalidad','bienestar','impuesto'],'una externalidad aparece cuando una decisión privada afecta a terceros. Si es negativa, el coste social supera al coste privado y el mercado tiende a producir demasiado.'],
    [['bien publico','no rival','no excluible'],'los bienes públicos puros son no rivales y no excluibles. De ahí surgen problemas de free-riding y justificación de intervención pública.'],
    [['riesgo','incertidumbre','averso'],'en incertidumbre, un agente averso al riesgo valora la seguridad. Por eso puede preferir una cantidad cierta a una lotería con igual valor esperado.'],
    [['probabilidad','independiente','condicionada'],'en probabilidad conviene aplicar la definición exacta: independencia, unión, intersección y probabilidad condicionada no son lo mismo.'],
    [['esperanza','varianza','media','mediana'],'la esperanza resume el valor medio esperado y la varianza mide dispersión. Muchas preguntas buscan distinguir posición central de variabilidad.'],
    [['normal','t student','chi-cuadrado','distribucion'],'cada distribución se usa en contextos distintos: normal para aproximaciones y variables continuas, t para medias con varianza desconocida, chi-cuadrado para varianzas o bondad de ajuste.'],
    [['inferencia','intervalo de confianza'],'un intervalo de confianza se interpreta como propiedad del procedimiento en muestras repetidas, no como certeza absoluta sobre una muestra concreta.'],
    [['contraste','p-valor','hipotesis'],'el p-valor se calcula suponiendo verdadera la hipótesis nula. Un p-valor pequeño indica que los datos son poco compatibles con H0.'],
    [['error tipo i','error tipo 1'],'el error tipo I es rechazar una hipótesis nula que en realidad era cierta. Se controla con el nivel de significación.'],
    [['sesgo','insesgado','consistente'],'insesgadez se refiere al valor esperado del estimador; consistencia se refiere a su comportamiento cuando la muestra crece.'],
    [['correlacion'],'la correlación mide asociación lineal, no causalidad. Una correlación de -1 implica relación lineal negativa perfecta.'],
    [['mco','gauss-markov','regresion lineal'],'en MCO la clave es el supuesto de exogeneidad y los supuestos clásicos. Bajo Gauss-Markov, MCO es el mejor estimador lineal insesgado.'],
    [['endogeneidad','variable omitida','instrumento'],'la endogeneidad rompe la condición de exogeneidad y hace que MCO sea sesgado o inconsistente. Instrumentos válidos deben ser relevantes y exógenos.'],
    [['heterocedasticidad'],'la heterocedasticidad significa varianza no constante del error. Afecta sobre todo a errores estándar e inferencia si se usan fórmulas convencionales.'],
    [['autocorrelacion'],'la autocorrelación aparece cuando los errores están correlacionados en el tiempo. Es típica en series temporales y distorsiona la inferencia estándar.'],
    [['multicolinealidad'],'la multicolinealidad alta dificulta separar efectos individuales de regresores correlacionados y suele aumentar errores estándar.'],
    [['r2','coeficiente de determinacion'],'el R² mide ajuste dentro de la muestra, no causalidad ni ausencia de sesgo. Un R² alto no garantiza que el modelo sea correcto.'],
    [['dummy','variable ficticia'],'una variable dummy transforma una categoría en valores 0/1 para poder incorporarla a una regresión.'],
    [['serie temporal','estacionaria','arima','ar(1)'],'en series temporales importa la dependencia temporal. Estacionariedad, rezagos y componentes AR/MA ayudan a modelar esa estructura.'],
    [['panel','efectos fijos'],'los datos de panel combinan individuos y tiempo. Los efectos fijos controlan factores inobservables constantes en el tiempo.'],
    [['sistema financiero','instituciones financieras','intermediarios'],'el sistema financiero canaliza ahorro hacia inversión, transforma plazos y riesgos y facilita pagos. Las instituciones se diferencian por función, balance y regulación.'],
    [['mercado monetario','mercados financieros','renta fija','bono','obligacion'],'en mercados financieros hay que distinguir instrumentos por plazo, riesgo, liquidez y derechos que generan. La renta fija paga flujos pactados, aunque su precio fluctúe.'],
    [['matematicas financieras','interes','descuento','capitalizacion','tir','van'],'en matemáticas financieras se comparan flujos en distintos momentos. La clave es actualizar o capitalizar usando el tipo de interés adecuado.'],
    [['ratio','porcentaje','descuento','crecimiento'],'en razonamiento numérico conviene convertir todo a una misma base. Los porcentajes sucesivos se multiplican, no se suman sin más.'],
    [['serie','secuencia','patron'],'en secuencias lógicas hay que buscar diferencias, multiplicadores o patrones alternos. La opción correcta mantiene la regla detectada.'],
    [['silogismo','todos','ningun','algunos'],'en silogismos solo se puede concluir lo que se deduce necesariamente de las premisas. Evita asumir más de lo que el enunciado permite.'],
    [['verbal','comprension','sinonimo','inferencia'],'en razonamiento verbal la respuesta correcta debe ser compatible con el texto literal. No conviene añadir supuestos que el enunciado no da.']
  ];
  for(const [keys,msg] of rules){if(keys.some(k=>text.includes(norm(k))))return `La opción ${q.answer} encaja porque: “${correctText(q)}”. ${msg}`}
  if(q.type==='capacidades')return `La opción ${q.answer} encaja porque: “${correctText(q)}”. La clave es seguir la relación lógica o numérica exacta y descartar opciones que añaden supuestos.`;
  if(q.type==='apoyo')return `La opción ${q.answer} encaja porque: “${correctText(q)}”. Es una pregunta de apoyo: te ayuda a entender el lenguaje financiero e institucional que suele rodear al Banco de España.`;
  return `La opción ${q.answer} encaja porque: “${correctText(q)}”. Esta pregunta evalúa una definición o relación básica del bloque ${q.section}; quédate con la idea central y no solo con la letra.`;
}
function go(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('#title').textContent={panel:'Panel',test:'Hacer test',fallos:'Registro de fallos',banco:'Banco de preguntas',ajustes:'Ajustes'}[v]||'Panel';$('#sidebar').classList.remove('open');renderAll()}
function getPool(tipo,bloque){let p=tipo==='fallos'?activeMistakes():questions.filter(q=>q.type===tipo);return bloque&&bloque!=='Todos los bloques'?p.filter(q=>q.section===bloque):p}
function fillBloques(){let tipo=$('#tipo').value,prev=$('#bloque')?.value,p=getPool(tipo);let secs=['Todos los bloques',...[...new Set(p.map(q=>q.section))].sort()];$('#bloque').innerHTML=secs.map(s=>`<option ${s===prev?'selected':''}>${s}</option>`).join('');$('#penaliza').checked=tipo!=='capacidades';updatePoolInfo()}
function updatePoolInfo(){let tipo=$('#tipo').value,bloque=$('#bloque').value,num=+$('#num').value||20,p=getPool(tipo,bloque),r=new Set(state.recentQuestions||[]),fresh=p.filter(q=>!r.has(q.id)).length;let msg=`Banco disponible: ${p.length} preguntas`;if(tipo!=='fallos')msg+=` · no vistas recientemente: ${fresh}`;if(num>p.length)msg+=` · has pedido ${num}, se usarán ${p.length}`;if(p.length<15&&tipo!=='fallos')msg+=' · este bloque es pequeño';$('#poolInfo').textContent=msg}
function startFromForm(){startTest({tipo:$('#tipo').value,bloque:$('#bloque').value,modo:$('#modo').value,num:+$('#num').value||20,secs:+$('#secs').value||75,penaliza:$('#penaliza').checked,noRepeat:$('#noRepeat').checked})}
function selectPool(pool,cfg){let target=Math.min(cfg.num,pool.length);if(!cfg.noRepeat||cfg.tipo==='fallos')return shuffle(pool).slice(0,target);let r=new Set(state.recentQuestions||[]);return [...shuffle(pool.filter(q=>!r.has(q.id))),...shuffle(pool.filter(q=>r.has(q.id)))].slice(0,target)}
function startTest(cfg){let p=getPool(cfg.tipo,cfg.bloque);if(!p.length){alert('No hay preguntas para esa selección.');return}let original=p.length;p=selectPool(p,cfg);if(cfg.num>original)alert(`Solo hay ${original} preguntas para esa selección. Harás ${p.length}.`);test={cfg,qs:p.map(q=>({...q,options:shuffle(q.options)})),i:0,ans:{},notes:{},end:Date.now()+p.length*cfg.secs*1000,timer:null};$('#setup').classList.add('hidden');$('#resultado').classList.add('hidden');$('#runner').classList.remove('hidden');tick();test.timer=setInterval(tick,500);renderQ()}
function tick(){if(!test)return;let r=Math.max(0,test.end-Date.now());$('#timer').textContent=String(Math.floor(r/60000)).padStart(2,'0')+':'+String(Math.floor((r%60000)/1000)).padStart(2,'0');if(r<=0)finish()}
function renderQ(){let q=test.qs[test.i],a=test.ans[q.id];$('#meta').textContent=`${test.i+1}/${test.qs.length} · ${test.cfg.tipo}`;$('#rTitulo').textContent=q.section;$('#prog').style.width=(test.i+1)/test.qs.length*100+'%';$('#fuente').textContent=q.source+(q.official?' · oficial':'');$('#tema').textContent=q.topic;$('#enunciado').textContent=q.question;$('#nota').value=test.notes[q.id]||state.notes[q.id]||'';$('#opciones').innerHTML=q.options.map(o=>`<button class="option ${a===o.key?'selected':''}" data-k="${o.key}"><span class="letter">${o.key}</span><span>${escapeHtml(o.text)}</span></button>`).join('')+'<div id="fb"></div>';$$('.option').forEach(b=>b.onclick=()=>{test.ans[q.id]=b.dataset.k;renderQ()});$('#prev').disabled=test.i===0;$('#next').textContent=test.i===test.qs.length-1?'Ver resultado':'Siguiente';feedback()}
function feedback(){let q=test.qs[test.i],a=test.ans[q.id],fb=$('#fb');if(test.cfg.modo!=='practica'||!a){fb.innerHTML='';return}$$('.option').forEach(b=>{if(b.dataset.k===q.answer)b.classList.add('correct');if(b.dataset.k===a&&a!==q.answer)b.classList.add('wrong')});let ok=a===q.answer,exp=escapeHtml(explanationFor(q));fb.className='feedback '+(ok?'ok':'bad');fb.innerHTML=ok?`<strong>Correcta.</strong><br><span>${exp}</span>`:`<strong>Fallada.</strong> Correcta: <strong>${q.answer}</strong>.<br><span>${exp}</span>`}
function move(d){let q=test.qs[test.i];test.notes[q.id]=$('#nota').value.trim();if(d>0&&test.i===test.qs.length-1)return finish();test.i=Math.max(0,Math.min(test.qs.length-1,test.i+d));renderQ()}
function finish(){if(!test)return;clearInterval(test.timer);let qcur=test.qs[test.i];if(qcur)test.notes[qcur.id]=$('#nota').value.trim();let correct=0,wrong=0,blank=0,score=0,topics={};for(let q of test.qs){let a=test.ans[q.id]||null,ok=a===q.answer;if(!a)blank++;else if(ok)correct++;else wrong++;score+=ok?1:(!a?0:(test.cfg.penaliza?-0.33:0));let k=q.section+' · '+q.topic;topics[k]??={seen:0,ok:0,wrong:0};topics[k].seen++;if(ok)topics[k].ok++;else if(a)topics[k].wrong++;if(test.notes[q.id])state.notes[q.id]=test.notes[q.id];if(a&&!ok){let m=state.mistakes[q.id]||{questionId:q.id,timesWrong:0,timesSeen:0,selected:[],firstWrongAt:new Date().toISOString()};m.timesWrong++;m.timesSeen++;m.lastWrongAt=new Date().toISOString();m.selected.push({answer:a,at:new Date().toISOString()});state.mistakes[q.id]=m;delete state.mastered[q.id]}else if(state.mistakes[q.id])state.mistakes[q.id].timesSeen=(state.mistakes[q.id].timesSeen||0)+1}let total=test.qs.length,grade=Math.max(0,score/total*10),ids=test.qs.map(q=>q.id),att={at:new Date().toISOString(),type:test.cfg.tipo,section:test.cfg.bloque,total,correct,wrong,blank,score,grade,penalty:test.cfg.penaliza,questionIds:ids};state.attempts.push(att);state.recentQuestions=[...ids,...(state.recentQuestions||[]).filter(id=>!ids.includes(id))].slice(0,250);state.daily[today()]=(state.daily[today()]||0)+total;test=null;save();$('#runner').classList.add('hidden');$('#setup').classList.remove('hidden');showResult(att,topics)}
function showResult(a,topics){let rows=Object.entries(topics).sort((x,y)=>x[1].ok/x[1].seen-y[1].ok/y[1].seen).map(([k,v])=>`<tr><td>${escapeHtml(k)}</td><td>${v.ok}/${v.seen}</td><td>${pct(v.ok,v.seen)}%</td></tr>`).join('');$('#resultado').classList.remove('hidden');$('#resultado').innerHTML=`<h3>Resultado</h3><div class="resultgrid"><div><span>Nota</span><strong>${a.grade.toFixed(2)}</strong></div><div><span>Aciertos</span><strong>${a.correct}/${a.total}</strong></div><div><span>Fallos</span><strong>${a.wrong}</strong></div></div><p>${a.penalty?'Con penalización -0,33.':'Sin penalización.'}</p><table><thead><tr><th>Tema</th><th>Aciertos</th><th>%</th></tr></thead><tbody>${rows}</tbody></table><div class="actions"><button class="primary" onclick="go('fallos')">Ver fallos</button><button class="secondary" onclick="go('test')">Otro test</button></div>`}
function streak(){let d=new Date(),s=0;while((state.daily[d.toISOString().slice(0,10)]||0)>0){s++;d.setDate(d.getDate()-1)}return s}
function renderPanel(){let done=state.attempts.reduce((s,a)=>s+a.total,0),ok=state.attempts.reduce((s,a)=>s+a.correct,0),vivos=activeMistakes().length,acc=pct(ok,done);$('#sPreg').textContent=done;$('#sAcc').textContent=acc+'%';$('#sFallos').textContent=vivos;$('#sRacha').textContent=streak();$('#dominio').textContent=(done?Math.max(0,Math.min(100,Math.round(acc-vivos*.5))):0)+'%';$('#dominioSub').textContent=vivos?`${vivos} fallos por repasar.`:(done?'Sin fallos vivos. Haz simulacro.':'Empieza un test.');let td=state.daily[today()]||0;$('#goalText').textContent=`${td} / ${state.settings.dailyGoal}`;$('#goalBar').style.width=Math.min(100,pct(td,state.settings.dailyGoal))+'%';renderHeat();renderReco()}
function renderHeat(){let map={};Object.values(state.mistakes).forEach(m=>{let q=qById(m.questionId);if(!q||state.mastered[q.id])return;let k=q.section+' · '+q.topic;map[k]=(map[k]||0)+(m.timesWrong||0)});let arr=Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,8);$('#heat').classList.toggle('empty',!arr.length);$('#heat').innerHTML=arr.length?arr.map(([k,v])=>`<div class="weak"><strong>${escapeHtml(k)}</strong><span>${v} fallos</span><div class="bar"><i style="width:${Math.min(100,v*18)}%"></i></div></div>`).join(''):'Sin datos todavía.'}
function renderReco(){let vivos=activeMistakes();if(vivos.length){let q=vivos[0];$('#reco').innerHTML=`<div class="rec"><strong>Ahora toca repasar fallos</strong><p>Tienes ${vivos.length} fallos vivos. Empieza por ${escapeHtml(q.section)} · ${escapeHtml(q.topic)}.</p><button class="primary" onclick="go('test');startTest({tipo:'fallos',bloque:'Todos los bloques',modo:'practica',num:10,secs:90,penaliza:true})">Repasar 10</button></div>`}else{$('#reco').innerHTML=`<div class="rec"><strong>Primer entrenamiento</strong><p>Haz 20 preguntas de conocimientos con feedback. Luego el sistema montará tu lista de fallos.</p><button class="primary" onclick="go('test')">Empezar</button></div>`}}
function renderFallos(){let term=norm($('#buscarFallos').value),status=$('#estadoFallos').value;let arr=Object.values(state.mistakes).map(m=>({m,q:qById(m.questionId)})).filter(x=>x.q).filter(({q})=>status==='todos'||(status==='dominados'?state.mastered[q.id]:!state.mastered[q.id]));if(term)arr=arr.filter(({q})=>norm(q.question+' '+q.topic+' '+q.section+' '+q.source).includes(term));arr.sort((a,b)=>new Date(b.m.lastWrongAt)-new Date(a.m.lastWrongAt));$('#listaFallos').classList.toggle('empty',!arr.length);$('#listaFallos').innerHTML=arr.length?arr.map(({m,q})=>`<article class="item"><header><div><h4>${escapeHtml(q.section)} · ${escapeHtml(q.topic)}</h4><span class="tag">${escapeHtml(q.source)}</span><span class="tag">${m.timesWrong} fallos</span>${state.mastered[q.id]?'<span class="tag">Dominada</span>':''}</div><button class="secondary" data-one="${q.id}">Repasar</button></header><p>${escapeHtml(q.question)}</p><p><strong>Correcta:</strong> ${q.answer}. <strong>Última tuya:</strong> ${m.selected?.at(-1)?.answer||'-'}</p><p class="hint"><strong>Contexto:</strong> ${escapeHtml(explanationFor(q))}</p><textarea rows="2" data-note="${q.id}" placeholder="Nota de memoria...">${escapeHtml(state.notes[q.id]||'')}</textarea><div class="actions"><button class="primary" data-save="${q.id}">Guardar nota</button><button class="secondary" data-master="${q.id}">${state.mastered[q.id]?'Reactivar':'Marcar dominada'}</button></div></article>`).join(''):'Aún no hay fallos registrados.';$$('[data-save]').forEach(b=>b.onclick=()=>{state.notes[b.dataset.save]=$(`[data-note="${b.dataset.save}"]`).value.trim();save()});$$('[data-master]').forEach(b=>b.onclick=()=>{state.mastered[b.dataset.master]?delete state.mastered[b.dataset.master]:state.mastered[b.dataset.master]=new Date().toISOString();save()});$$('[data-one]').forEach(b=>b.onclick=()=>{go('test');startSpecific(b.dataset.one)})}
function startSpecific(id){let q=qById(id);if(!q)return;test={cfg:{tipo:'fallos',modo:'practica',penaliza:true},qs:[{...q,options:shuffle(q.options)}],i:0,ans:{},notes:{},end:Date.now()+120000,timer:null};$('#setup').classList.add('hidden');$('#resultado').classList.add('hidden');$('#runner').classList.remove('hidden');tick();test.timer=setInterval(tick,500);renderQ()}
function renderBanco(){let total=questions.length,con=questions.filter(q=>q.type==='conocimientos').length,apo=questions.filter(q=>q.type==='apoyo').length,off=questions.filter(q=>q.official).length;$('#resumenBanco').innerHTML=`<article><span>Total</span><strong>${total}</strong></article><article><span>Conoc.</span><strong>${con}</strong></article><article><span>Apoyo</span><strong>${apo}</strong></article><article><span>Oficiales</span><strong>${off}</strong></article>`;let term=norm($('#buscarBanco').value),tipo=$('#tipoBanco').value;let arr=questions.filter(q=>tipo==='all'||q.type===tipo);if(term)arr=arr.filter(q=>norm(q.question+' '+q.topic+' '+q.section+' '+q.source).includes(term));$('#listaBanco').innerHTML=arr.slice(0,80).map(q=>`<article class="item"><header><div><h4>${escapeHtml(q.section)} · ${escapeHtml(q.topic)}</h4><span class="tag">${escapeHtml(q.source)}</span><span class="tag">${q.type}</span>${q.official?'<span class="tag">Oficial</span>':'<span class="tag">Simulacro</span>'}</div><strong>${q.answer||'?'}</strong></header><p>${escapeHtml(q.question)}</p><p class="hint"><strong>Explicación:</strong> ${escapeHtml(explanationFor(q))}</p></article>`).join('')+(arr.length>80?`<div class="empty">Mostrando 80 de ${arr.length}. Usa el buscador.</div>`:'')}
function renderAll(){renderPanel();renderFallos();renderBanco();fillBloques()}
function exportCsv(){let rows=[['bloque','tema','fuente','pregunta','correcta','explicacion','veces_fallada','ultima_fecha','nota']];Object.values(state.mistakes).forEach(m=>{let q=qById(m.questionId);if(q)rows.push([q.section,q.topic,q.source,q.question,q.answer,explanationFor(q),m.timesWrong,m.lastWrongAt,state.notes[q.id]||''])});download('fallos-bde.csv',rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n'),'text/csv')}
function importProgress(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{state={...clone(blank),...JSON.parse(r.result)};save();alert('Progreso importado.')}catch{alert('JSON no válido')}};r.readAsText(f)}
function importQuestions(){try{let incoming=JSON.parse($('#importPregs').value);if(!Array.isArray(incoming))throw 0;saveCustom([...loadCustom(),...incoming]);$('#importPregs').value='';alert(`${incoming.length} preguntas importadas.`)}catch{alert('JSON no válido.')}}
function addManual(e){e.preventDefault();let q={id:'MAN_'+Date.now(),source:'Manual',number:0,type:'conocimientos',section:$('#mSec').value||'Manual',topic:$('#mTopic').value||'Sin tema',question:$('#mQ').value,options:['A','B','C','D'].map(k=>({key:k,text:$(`#m${k}`).value})),answer:$('#mAns').value,explanation:'',official:false};if(!q.question||q.options.some(o=>!o.text)){alert('Completa pregunta y opciones.');return}saveCustom([...loadCustom(),q]);$('#modal').close()}
function init(){$$('.nav').forEach(b=>b.onclick=()=>go(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#menu').onclick=()=>$('#sidebar').classList.toggle('open');$('#tipo').onchange=fillBloques;$('#bloque').onchange=updatePoolInfo;$('#num').oninput=updatePoolInfo;$('#noRepeat').onchange=updatePoolInfo;$('#start').onclick=startFromForm;$('#startFallos').onclick=()=>startTest({tipo:'fallos',bloque:'Todos los bloques',modo:'practica',num:10,secs:90,penaliza:true});$('#doFallos').onclick=()=>{go('test');startTest({tipo:'fallos',bloque:'Todos los bloques',modo:'practica',num:20,secs:90,penaliza:true})};$('#prev').onclick=()=>move(-1);$('#next').onclick=()=>move(1);$('#blank').onclick=()=>{let q=test.qs[test.i];delete test.ans[q.id];renderQ()};$('#finish').onclick=finish;$('#buscarFallos').oninput=renderFallos;$('#estadoFallos').onchange=renderFallos;$('#buscarBanco').oninput=renderBanco;$('#tipoBanco').onchange=renderBanco;$('#csv').onclick=exportCsv;$('#exportJson').onclick=()=>download('bde-test-lab-progreso.json',JSON.stringify(state,null,2));$('#importJson').onchange=importProgress;$('#reset').onclick=()=>{if(confirm('¿Seguro? Se borrará tu progreso.')){state=clone(blank);save()}};$('#importBtn').onclick=importQuestions;$('#manualBtn').onclick=()=>$('#modal').showModal();$('#mSave').onclick=addManual;if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#install').hidden=false});$('#install').onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#install').hidden=true}};renderAll()}
async function boot(){if(window.BDE_QUESTIONS_READY)await window.BDE_QUESTIONS_READY;questions=[...(window.BDE_QUESTIONS||[]),...loadCustom()];init()}
document.addEventListener('DOMContentLoaded',boot);
